spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/rabcdb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: qwe14782935
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 50
        max-wait: 5000ms
    host: 192.168.208.129
    port: 6379
    sentinel:
      master: mymaster
      nodes: 192.168.208.129:26379,192.168.208.129:26380,192.168.208.129:26381